arreglo_cursos = [['TALLER DE COMPRENSION LECTORA',
                   'CALCULO DIFERENCIAL',
                   'QUIMICA GENERAL',
                   'MATEMATICAS BASICAS',
                   'FUNDAMENTOS DE PROGRAMACION'],
                  ['CALCULO INTEGRAL',
                   'FISICA MECANICA',
                   'ALGEBRA LINEAL',
                   'PROGRAMACION',
                   'INGLES I'],
                  ['TALLER DE ESCRITURA ACADEMICA',
                   'CALCULO VECTORIAL',
                   'FISICA II',
                   'PROGRAMACION ORIENTADA A OBJET',
                   'INGLES II'],
                  ['ECUACIONES DIFERENCIALES Y EN',
                   'FISICA III',
                   'MATEMATICA DISCRETA',
                   'ESTRUCTURA DE DATOS',
                   'INGLES III'],
                  ['CONSTITUCION POLITICA',
                   'ESTADISTICA Y PROBABILIDAD',
                   'BASE DE DATOS',
                   'INGLES IV'],
                  ['CREATIVIDAD Y EMPRENDIMIENTO',
                   'ESTADISTICA INFERENCIAL',
                   'COMUNICACIONES Y REDES',
                   'PROCESAMIENTO NUMERICO',
                   'ARQUITECTURA DE SOFTWARE',
                   'INGLES V'],
                  ['GESTION DE PROYECTOS',
                   'CIUDADANIA GLOBAL',
                   'ARQUITECTURA DEL COMPUTADOR',
                   'SISTEMAS Y MODELOS',
                   'INGENIERIA DE SOFTWARE'],
                  ['SISTEMAS OPERATIVOS',
                   'INTELIGENCIA ARTIFICIAL'],
                  ['TOP ESPE DE CIENCIAS COMPUTACI'],
                  ['ETICA',
                   'PRACTICA PROFESIONAL']]
